### ISSUE TITLE
cannot connect to X server localhost:10.0

### ISSUE THREAD

**Issue by xiechuanyu** [SensorsINI/ddd20-utils#4]
When I run `python export_ddd20_hdf.py`.
An error occurs `: cannot connect to X server localhost:10.0`.

It seems that this script needs to run on GUI.
But my remote server doesn`t have GUI.

**Comment by tobidelbruck** [comment]
I think you need to turn off the preview output. I don't remember the 
command line option or if there is one. I guess you are running on a 
remote server with no display?

In any case the edit to turn off the preview should be pretty simple.
