### ISSUE TITLE
Data Processing

### ISSUE THREAD

**Issue by chensong1995** [SensorsINI/ddd20-utils#8]
Hello there!

Thank you for all the efforts in creating DDD20. I am greatly inspired by your work, and would like to test a newly developed method on this dataset. However, I encountered some difficulties in creating the training/testing split.

I generated 30 .hdf5 files using [this script on GitHub](https://github.com/SensorsINI/ddd20-utils/blob/master/export-data-ral.sh). After that, I attempted to create the training/testing split. [The code on GitHub](https://github.com/SensorsINI/ddd20-utils/blob/e783fe516b189fcbeb1115287ca8892eeccfc99d/hdf5_deeplearn_utils.py#L88) appears to be inconsistent with Section III-A in your paper, so I wrote a short script which is attached to this email for your reference. It can be executed with `python generate_meta.py` if you put the script in the same directories as all exported .hdf5 files. In summary, the script does the following:

1. Read in the 30 .hdf5 files generated by export-data-ral.sh
2. Trim with [real endpoints](https://github.com/SensorsINI/ddd20-utils/blob/e783fe516b189fcbeb1115287ca8892eeccfc99d/hdf5_deeplearn_utils.py#L11)
3. Compute the mean and standard deviation of the steering wheel angle
4. For each recording, take the first 70% as training and the rest as testing
5. Eliminate examples with speed < 15km/h
6. Eliminate examples with angle outside the 3-sigma range
7. On the training split, randomly prune 70% of frames that have steering angles between +-5 degrees
8. I did a sanity check to verify the correctness of my split. I computed the RMSE using null prediction, and get 18.95 on the training split, and 17.85 on the testing split. This appears to be different from the statistics reported in your paper, which is 11.

At your convenience, can you provide some hints on what may have gone wrong here? Alternatively, it can also be helpful if you can share your script that splits the dataset.

[generate_meta.zip](https://github.com/SensorsINI/ddd20-utils/files/5791850/generate_meta.zip)

Sincerely,
Chen

**Comment by tobidelbruck** [comment]
Dear Chen, Thanks for your comments. I think Yuhuang could help with 
this. -Tobi

**Comment by duguyue100** [comment]
Hi, @chensong1995, sorry for keeping you waiting. Thanks for your implementation.
The actual training and data processing procedures for this paper is actually kept in this repository: https://github.com/duguyue100/ddd20-itsc20
I've just made it public. (As you can see, it still follows DDD20's previous name, DDD17+)

For processing the data, the script is here: https://github.com/duguyue100/ddd20-itsc20/blob/master/scripts/ddd17_data_processor.py

The main difference between your implementation and mine is the `frame_cuts` in the above script.
It manually trims starting and lasting frames from the dataset because I remembered that there are some irregularities found (by watching the raw recordings).
This was explained in the first draft, and we finally dropped it because of space (maybe it's still in the supplementary material, I can't recall, sorry).

With this, you should be able to reduce the null prediction.

Yuhuang.

**Comment by chensong1995** [comment]
Thanks for your prompt reply! I was unable to run the script as the (proprietary?) package `spiker` is missing in my environment. However, the overall logic is clear to me, and I was able to add a few lines in my code to trim based on `frame_cuts`. The new statistics are:

```
raw frame count: 327948
raw train frame count: 291419
raw test frame count: 36529
raw angle mean: -0.11607775275348535 std: 21.805444443757484
filtered train frame count: 271542
filtered test frame count: 35586
train rmse: 11.794671058654785
test rmse: 12.279165267944336
all rmse: 11.851823806762695
```

This looks pretty close to 11, which is the figure reported in your paper. There are a few things I would like to confirm:

1. The numbers here are still a little bit higher than your reported statistics. Do they look good to you?

2. On [this line](https://github.com/duguyue100/ddd20-itsc20/blob/master/scripts/ddd17_data_processor.py#L115), it appears that the threshold on small angles is 5 radians, not 5 degrees. This is inconsistent with Section II-A-2) in the paper. Despite this (possible typo in the paper), I believe the raw data and RMSE are both given in degrees. Am I right here?

3. How exactly is the argument `frame_cut` used by `ddd17.prepare_train_data()`? Is my guess here correct?
```
start, end := frame_cuts
length := real_end_point(h5f['timestamp']) 
angle := h5f['steering_wheel_angle'][:length][(start*2):(-end*2)]
```

My new script is attached for your reference. May I ask for some further hints on these questions? Thank you!
[generate_meta_frame_cut.zip](https://github.com/SensorsINI/ddd20-utils/files/5798463/generate_meta_frame_cut.zip)

**Comment by duguyue100** [comment]
Spiker is a long-abandoned event processing module I wrote.

1. The statistics look alright to me. 11 degrees is a round-down number I believe. There might be some small calculation differences.

2. To your second question, the dataset is recorded in radians, so `small_degree = 5.*np.pi/180.` actually corresponds to 5 degrees. And yes, all RMSEs in the paper are given in degrees.

3. The exact implementation of this `prepare_train_data()` is here: https://github.com/duguyue100/spiker/blob/master/spiker/data/ddd17.py#L129 (). Here is the code block that uses the frame cut: https://github.com/duguyue100/spiker/blob/master/spiker/data/ddd17.py#L148-L201

**Comment by chensong1995** [comment]
Thanks for your reply!

You are right -- this is a conversion from degrees to radians, and the threshold is indeed 5 degrees. However, Table I in your paper states that the (raw) steering wheel angle is given in degrees. The range of steering wheel angles on the dataset is [-446.4, 421.9]. This will be enormously large if it is in radians. Also, the number 11 I obtained above was computed based on the raw data unit. If the dataset is recorded in degrees, the RMSE I obtained would be 11 radians instead of 11 degrees too. Would you mind double-check this again, please?

I was unable to access the spiker repository possibly because it is set to private.

**Comment by duguyue100** [comment]
Yeah, sorry for the confusion. I've made the spiker public.

By looking at the following lines 
https://github.com/duguyue100/spiker/blob/master/spiker/data/ddd17.py#L159-L162

```python
if y_name == "steering":
    Y = data_file["steering_wheel_angle"][()][..., np.newaxis][
        first_f:-last_f]
    Y = Y/180.*np.pi
```

The story was applying regression on raw degrees is ineffective (the range is too large). So I first changed the degrees to radians, and when I report the results, it's reported in degrees.

**Comment by chensong1995** [comment]
The script you provided was very helpful. It helped me identify a few issues in the data processing script I had earlier. I am now able to train a neural network that reproduces similar performance as reported in your paper. Interestingly, in my implementation, the RMSE and EVA using degrees are slightly better than using radians. They are both on par with what is reported in Table II of your paper, though.

Once again, thanks for your help!

**Comment by tobidelbruck** [comment]
Thanks a lot for your feedback Song. It's great to year you can 
reproduce the results. Good luck with your developments.
